<a href="https://colab.research.google.com/github/Pathornnnnn/pro_fund/blob/main/Lab_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015105     ชื่อ : นาย ภาธร สมแสน

1.	เขียนฟังก์ชัน add_score(subject_score, subject, score) โดยมีพารามิเตอร์ 3 ตัว ได้แก่ subject_score เป็น dictionary ที่มีคู่ key : value เป็น subject : score พารามิเตอร์ตัวที่ 2 และ 3 เป็น subject และ score โดย subject เป็น string และ score เป็น integer โดยให้นำ subject และ score ไปเพิ่มใน dictionary เช่น

-Input : subject_score = { }, subject = ‘python’, score = 50
-return : { ‘python’ : 50 }
-input : subject_score = { ‘python’ : 50 }, subject = ‘calculus’, score = 60
-return : { ‘python’ : 50, ‘calculus : 60 }


จากนั้นให้เขียนฟังก์ชัน calc_average_score หาค่าเฉลี่ยของคะแนนในทุกรายวิชาใน dictionary ที่ได้จากฟังก์ชัน add_score โดยให้ส่งค่าคืนมาเป็น string ที่มีทศนิยม 2 ตำแหน่ง


In [ ]:
def add_score(subject_score, student, subject, score):
    if student not in subject_score:
        subject_score[student] = {}
    subject_score[student][subject] = score
    return subject_score

dict = {}
add_score(dict,'65010001', 'python', 50) # => {'65010001' : { 'python' : 50 } }
add_score(dict,'65010001', 'calculus', 60) # => {'65010001' : { 'python' : 50, 'calculus' : 60 }
print(dict)



def calc_average_score(subject_score):
  avg = 0
  for i in subject_score:
    len_std = len(subject_score[i])
    for j in subject_score[i]:
       avg += subject_score[i][j]
    avg /= len_std
    return '{:.2f}'.format(avg)

calc_average_score(dict) # => {'65010001': '55.00' }


{'65010001': {'python': 50, 'calculus': 60}}


'55.00'

2.	ให้นำโปรแกรมตามข้อ 1 มาขยายความสามารถให้รองรับนักศึกษาหลายคน โดยให้ refactor ฟังก์ชัน add_score ให้รับพารามิเตอร์เป็น add_score(subject_score, student, subject, score) โดย student เป็นข้อมูลของนักศึกษาเป็น string (ในที่นี้เป็น id) และ return เป็น dictionary

- Input : subject_score = { }, student = '65010001', subject = 'python', score = 50
- return : { '65010001' : { 'python' : 50 } }
- input : subject_score = { '65010001' : { 'python' : 50 } },
  student = '65010001', subject = ‘calculus’, score = 60
- return : {'65010001': {'python’: 50,  'calculus', 60} }

โดยหากชื่อมีข้อมูล key ใดที่มีใน dictionary อยู่แล้ว ให้ถือเป็นการ update ข้อมูลนั้น

ให้ refactor ฟังก์ชัน calc_average_score โดยให้ส่งคืนเป็น dictionary ของนักศึกษาและคะแนนเฉลี่ยของนักศึกษาคนนั้น เช่น {'65010001': '55.00' }


In [ ]:
def add_score(subject_score, student, subject, score):
    subject = subject.lower()
    if student not in subject_score:
        subject_score[student] = {}
    subject_score[student][subject] = score

    return subject_score

dict = {}
add_score(dict,'65010001', 'python', 50) # => {'65010001' : { 'python' : 50 } }
add_score(dict,'65010001', 'calculus', 60) # => {'65010001' : { 'python' : 50, 'calculus' : 60 }
add_score(dict,'65010001','eng',30)
add_score(dict,'65010001','Eng',40)


def calc_average_score(subject_score):
  avg = 0
  for i in subject_score:
    len_std = len(subject_score[i])
    for j in subject_score[i]:
       avg += subject_score[i][j]
    avg /= len_std
    return '{:.2f}'.format(avg)

print(dict)
print(calc_average_score(dict)) # => {'65010001': '55.00' }


{'65010001': {'python': 50, 'calculus': 60, 'eng': 40}}
50.00


3.	ให้เขียนฟังก์ชัน is_plusone_dictionary(d) โดยรับพารามิเตอร์ 1 ตัว เป็นข้อมูลชนิด dictionary และให้ทดสอบว่า dictionary ที่รับเข้ามาเป็น plusone dictionary หรือไม่ ผลลัพธ์ให้ return เป็น True หรือ False โดย plusone dictionary คือ dictionary ที่ key และ value จะบวก 1 ต่อกันไปเรื่อยๆ  

- Input :   {1:2, 3:4, 5:6, 7:8}
- return : True

อธิบาย : เพราะ key : value ต่างกันเป็น +1 ต่อกันไป
- Input :   {1:2, 3:10, 5:6, 7:8}
- return : False

อธิบาย : เพราะ key, value ไม่เป็นไปตามลำดับ


In [ ]:
def is_plusone_dictionary(d):
  pass

is_plusone_dictionary({1:2, 3:4, 5:6, 7:8}) # => True
is_plusone_dictionary({1:2, 3:10, 5:6, 7:8}) # => False



4.	เขียนฟังก์ชัน char_count(str) โดยรับพารามิเตอร์ 1 ตัว เป็นข้อมูลชนิด string และให้ส่งคืนเป็น dictionary ที่มี key เป็นตัวอักษรแต่ละตัวของ string นั้น และ value คือ จำนวนครั้งที่ตัวอักษรนั้นปรากฏใน string เช่น

- Input : 'language'
- return : {'l': 1, 'a': 2, 'n': 1, 'g': 2, 'e': 1}


In [ ]:
def char_count(str):
  pass

char_count('language') # => {'l': 1, 'a': 2, 'n': 1, 'g': 2, 'e': 1}

char_count('awesome') # => {'a': 1, 'e': 2, 'm': 1, 'o': 1, 'w': 1}

char_count('me') # => {'m': 1, 'e': 1}

5.	ข้อมูลต่อไปนี้แทน music album แต่ละ album เก็บใน dictionary ซึ่งมีตัวเลข id เป็น key โดยแต่ละ album ไม่จำเป็นต้องมีข้อมูลครบ



```
record_collection = {
  2548: {
    albumTitle: 'Slippery When Wet',
    artist: 'Bon Jovi',
    tracks: ['Let It Rock', 'You Give Love a Bad Name']
  },
  2468: {
    albumTitle: '1999',
    artist: 'Prince',
    tracks: ['1999', 'Little Red Corvette']
  },
  1245: {
    artist: 'Robert Palmer',
    tracks: []
  },
  5439: {
    albumTitle: 'ABBA Gold'
  }
```



ให้เขียนฟังก์ชัน update_records โดยรับพารามิเตอร์ 4 ตัว คือ 1) dictionary record 2) id 3) property (เช่น artist หรือ tracks 4) value โดยหน้าที่ของฟังก์ชัน คือ ให้เพิ่ม/เปลี่ยน ค่า property และ value ของ album ของ id ที่ส่งค่าไปในฟังก์ชัน โดยมีรายละเอียดดังนี้
- ฟังก์ชันจะต้องส่งคืนข้อมูล record ทั้งหมดกลับมา
- ถ้า property ไม่ใช่ tracks และ value ไม่ใช่ empty string ให้ update หรือ set ข้อมูล property กับ value ใน album นั้น
- ถ้า property เป็น tracks แต่ album นั้นไม่มี tracks property ให้สร้าง List ใหม่และเพิ่มข้อมูลเข้าไปใน List นั้น
- ถ้า property เป็น tracks และ value ไม่ใช่  empty string ให้เพิ่ม value ต่อท้ายใน List ของ tracks  
- ถ้า value เป็น empty string ให้ลบข้อมูล property นั้นออกจาก album




In [ ]:
record_collection = {
  2548: {
    'albumTitle': 'Slippery When Wet',
    'artist': 'Bon Jovi',
    'tracks': ['Let It Rock', 'You Give Love a Bad Name']
  },
  2468: {
    'albumTitle': '1999',
    'artist': 'Prince',
    'tracks': ['1999', 'Little Red Corvette']
  },
  1245: {
    'artist': 'Robert Palmer',
    'tracks': []
  },
  5439: {
    'albumTitle': 'ABBA Gold'
  }
}

def update_records(record, id, property, value):
  if property != 'tracks' and value != '':
    record[id][property] = value
  elif property == 'tracks' and 'tracks' not in record[id]:
      record[id][property] = value
  elif property == 'tracks' and value != '':
    if type(value) == list:
      record[id][property].extend(value)
    else:
      record[id][property].append(value)
  elif value == '':
    del record[id][property]
  return record

update_records(record_collection, 2548, 'a7
\rtist', '') # ลบ artist ของ 2548
update_records(record_collection, 2548, 'artist', 'Sting') # แก้ไข artist ของ 2548
update_records(record_collection, 2548, 'tracks', 'wanted dead or alive') # เพิ่ม tracks ของ 1245
update_records(record_collection, 2548, 'tracks', ['sadasd','sadasd']) # ลบ tracks ของ 1245
# update_records(record_collection, 5439, 'tracks', 'I Put a Spell on You') # เพิ่ม tracks ของ 5439
# update_records(record_collection, 5439, 'artist', 'ABBA') # เพิ่ม artist ของ 5439
# update_records(record_collection, 5439, 'artist', 'Chicago') # แก้ไข artist ของ 5439
# update_records(record_collection, 1245, 'tracks', 'Addicted to Love') # เพิ่ม tracks ของ 1245
# update_records(record_collection, 5439, 'albumTitle', '') # ลบ albumTitle ของ 5439

print(record_collection)



{2548: {'albumTitle': 'Slippery When Wet', 'tracks': ['Let It Rock', 'You Give Love a Bad Name', 'wanted dead or alive', 'sadasd', 'sadasd'], 'artist': 'Sting'}, 2468: {'albumTitle': '1999', 'artist': 'Prince', 'tracks': ['1999', 'Little Red Corvette']}, 1245: {'artist': 'Robert Palmer', 'tracks': []}, 5439: {'albumTitle': 'ABBA Gold'}}


ให้เขียนโปรแกรม หาขนาดไฟล์แต่ละไฟล์และขนาดไฟล์รวมใน directory
https://github.com/khthana/Python67/blob/main/thai-handwritten-dataset.zip




In [ ]:
!git clone https://github.com/khthana/Python67/

Cloning into 'Python67'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 33 (delta 11), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (33/33), 12.32 MiB | 14.04 MiB/s, done.
Resolving deltas: 100% (11/11), done.


In [ ]:
from pathlib import Path
import os
print(Path.cwd)
!é


<bound method Path.cwd of <class 'pathlib.Path'>>
Archive:  /content/Python67/thai-handwritten-dataset.zip
replace /content/Python67/Dataset/thai-handwritten-dataset/0/0098326c-aa9e-410d-b949-e13d3cd74cfd.png? [y]es, [n]o, [A]ll, [N]one, [r]ename: 